services:
  app:
    image: cosmtrek/air
    working_dir: /app
    ports:
      - 8080:8080
    environment:
      LIVE_RELOAD: true
    volumes:
      - .:/app
  
  livereload:
    build:
      dockerfile: docker/Dockerfile.livereload
      context: .
    ports:
      - 5555:5555